name: ci with integration tests

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DB: customer_db

        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build and run tests
        run: mvn -B package

        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/customer_db_test
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          JWT_SECRET: 5367566859703373367639792F423F452848284D6251655468576D5A71347437
